name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 QEMU 以支持多架构
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 生成北京时间时间戳
      - name: Generate timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(TZ='Asia/Shanghai' date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      # 构建并推送 Docker 镜像（支持 arm64 和 amd64）
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64  # 指定构建 arm64 和 amd64 架构
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/beenote:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/beenote:${{ env.TIMESTAMP }}
